
# gRPC configuration — runs on its own Netty server, independent of the HTTP layer
quarkus.grpc.server.port=9000
quarkus.grpc.server.use-separate-server=true


quarkus.http.port=8082

# PostgreSQL datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:admin}
quarkus.datasource.password=${DB_PASSWORD:password}
quarkus.datasource.reactive.url=postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:books}